### ISSUE TITLE
无法导入配置

### ISSUE THREAD

**Issue by veryrich** [leitbogioro/v2ray.fun#1]
![image](https://user-images.githubusercontent.com/12951051/58532471-42059980-8218-11e9-8f3f-5a3643aef6f9.png)

您好，我使用导入功能无法正常导入配置，点击OK后，弹出提示 “tag direct is reserved, please use another one!”

使用的客户端版本是 Version 1.5.1 (1278)

**Comment by leitbogioro** [comment]
试试看windows版的v2ray呢？

**Comment by leitbogioro** [comment]
由于我没有 Mac 环境，所以无法测试链接导入到 v2rayU 是否正常
