### ISSUE TITLE
v2ray服务端监听错误

### ISSUE THREAD

**Issue by badtoken** [leitbogioro/v2ray.fun#3]
Proto | Recv-Q | Send-Q | Local Address | Foreign Address | State | PID/Program name    
tcp    |    0   |   0 | 127.0.0.1:41015   |       0.0.0.0:*     |          LISTEN    |  708/v2ray     

一键安装后，瞎鸡儿选传输方式，v2ray监听地址被覆盖为127.0.0.1，导致v2ray无法接收外部请求。

手动修改/etc/v2ray/config.json   
将listen:127.0.0.1改为0.0.0.0  OK了

**Comment by leitbogioro** [comment]
在写入json模块中“调整为tcp传输模式”选项里，将inbound中的listen参数强制拨回为null，问题已解决
