### ISSUE TITLE
read/write on closed pipe错误

### ISSUE THREAD

**Issue by benladen** [leitbogioro/v2ray.fun#4]
已经安装并运行，但是v2rayng安卓提示io : read/write on closed pipe
下面是查看状态，正常吗？感谢大神。
Redirecting to /bin/systemctl status v2ray.service
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-11-08 15:28:02 CST; 4min 6s ago
 Main PID: 27423 (v2ray)
   CGroup: /system.slice/v2ray.service
           └─27423 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json

Nov 08 15:28:02 ecs-wSW systemd[1]: Started V2Ray Service.
Nov 08 15:28:02 ecs-wSW v2ray[27423]: V2Ray 4.21.3 (V2Fly, a community-driven edition of V...tom
Nov 08 15:28:02 ecs-wSW v2ray[27423]: A unified platform for anti-censorship.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by benladen** [comment]
还需要放行哪个端口吗？

**Comment by leitbogioro** [comment]
服务端没问题，客户端抛出这个错误，很明显是流量特征被识别了而被干扰

**Comment by benladen** [comment]
> 服务端没问题，客户端抛出这个错误，很明显是流量特征被识别了而被干扰

so，可以解决吗？

**Comment by leitbogioro** [comment]
用websocket+tls咯，目前这个脚本不支持，得你自行安装nginx等分流
